<template>
  <div id="content">
    <h3>Show Perl5 CoreSmoke {{ fileType }}</h3>
  </div>
  <div v-if="isLoading" class="spinner" />
  <div v-if="!httpError && !isLoading">
    <div>
      <button
      style="margin: 1rem"
      @click="backToReport(reportId)">Back to report</button>

      <div class="show-report">
        <pre>{{ rd[fileType] }}</pre>

        <div class="report-footer">
          Report generated by {{ webName}} {{ webVersion }} / API {{ appVersion }}
        </div>
      </div>
    </div>
  </div>
  <div v-else-if="httpError" class="report-not-found">
  Report {{ reportId }} not found.
  </div>
</template>

<script>
import { mapGetters, mapActions } from 'vuex';
import { useRouter }              from 'vue-router';
import { logDebug }               from '@/helpers/logging';

export default {
  name: "ShowLogOrOutFile",
  props: {
    fileType: {type: String, required: true},
    reportId: {type: String, required: true},
  },
  setup() {
    const router = useRouter()
    const backToReport = function (id) {
      const reportId = parseInt(id);
      logDebug(`backToReport(${reportId})`);

      router.push({path: `/report/${reportId}`});
    };
    return { backToReport };
  },
  data() {
    return {
      isLoading: true,
      webVersion: import.meta.env.VITE_APP_VERSION,
      webName:    import.meta.env.VITE_APP_NAME,
    };
  },
  computed: {
    ...mapGetters({
      hasFullReport: "getFullReport/hasFullReport",
      rd: "getFullReport/reportData",
      hasVersion: "getVersion/hasVersion",
      appVersion: "getVersion/theVersion",
    }),
  },
  mounted() {
    logDebug(`Looking for ${this.reportId} (${this.rd.id}) [${this.hasFullReport}]`);
    if (!this.hasFullReport || this.rd.id != this.reportId) {
      this.getFullSmokeReportNow(this.reportId);
    }
    else {
      this.isLoading = false;
    }
    if (!this.hasVersion) { this.getVersionNow() }
  },
  methods: {
    ...mapActions({
      getFullReport: "getFullReport/getFullReport",
      getVersion: "getVersion/getVersion",
    }),
    async getFullSmokeReportNow(reportId) {
      this.isLoading = true;
      this.httpError = false;
      try {
        await this.getFullReport(reportId);
      } catch(e) {
        this.httpError = true;
        console.log(`HTTP-Error: ${JSON.stringify(e)}`);
      };
      logDebug(`getFullSmokeReportNow: ${JSON.stringify(this.rd)}`);
      this.isLoading = false;
    },
    async getVersionNow() {
      try {
        await this.getVersion();
      }
      catch(e) {
        console.log(`HTTP-Error: ${e}`);
      }
    },
  },
}
</script>
