<template>
  <div id="content">
    <h3>Show Perl5 CoreSmoke {{ fileType }}</h3>
  </div>
  <div>
    <button
    style="margin: 1rem"
    @click="backToReport(reportId)">Back to report</button>

    <div class="show-report">
      <pre>{{ rd[fileType] }}</pre>

      <div class="report-footer">
        Report generated by {{ webName}} {{ webVersion }} / API {{ appVersion }}
      </div>
    </div>
  </div>
</template>

<script>
import { mapGetters, mapActions } from 'vuex';
import { useRouter }              from 'vue-router';
import { logDebug }               from '@/helpers/logging';

export default {
  name: "ShowLogOrOutFile",
  props: {
    fileType: {type: String, required: true},
    reportId: {type: String, required: true},
  },
  setup() {
    const router = useRouter()
    const backToReport = function (id) {
      const reportId = parseInt(id);
      logDebug(`backToReport(${reportId})`);

      router.push({path: `/report/${reportId}`});
    };
    return { backToReport };
  },
  data() {
    return {
      webVersion: import.meta.env.VITE_APP_VERSION,
      webName:    import.meta.env.VITE_APP_NAME,
    };
  },
  computed: {
    ...mapGetters({
      rd: "getFullReport/reportData",
      hasVersion: "getVersion/hasVersion",
      appVersion: "getVersion/theVersion",
    }),
  },
  mounted() {
    if (!this.hasVersion) { this.getVersionNow() }
  },
  methods: {
    ...mapActions({
      getVersion: "getVersion/getVersion",
    }),
    async getVersionNow() {
      try {
        await this.getVersion();
      }
      catch(e) {
        console.log(`HTTP-Error: ${e}`);
      }
    },
  },
}
</script>
