<template>
  <div id="content">
    <h3>Show Perl5 CoreSmoke {{ fileType }}</h3>
  </div>
  <div v-if="isLoading" class="spinner" />
  <div v-if="!isLoading">
    <button
    style="margin: 1rem"
    @click="backToReport(reportId)">Back to report</button>

    <div class="show-report">
      <pre>{{ file.content }}</pre>
    
      <div class="report-footer">Report generated by {{ webName}} {{ webVersion }}</div>
    </div>
  </div>
</template>

<script>
import { mapGetters, mapActions } from 'vuex';
import { useRouter }              from 'vue-router';
import { logDebug }               from '@/helpers/logging';

export default {
  name: "ShowLogOrOutFile",
  props: {
    fileType: {type: String, required: true},
    reportId: {type: String, required: true},
  },
  setup() {
    const router = useRouter()
    const backToReport = function (id) {
      const reportId = parseInt(id);
      logDebug(`backToReport(${reportId})`);

      router.push({path: `/report/${reportId}`});
    };
    return { backToReport };
  },
  data() {
    return {
      httpError: false,
      isLoading: true,
      webVersion: import.meta.env.VITE_APP_VERSION,
      webName:    import.meta.env.VITE_APP_NAME,
    };
  },
  computed: {
    ...mapGetters({
      file: 'getLogFileContent/file',
      hasContent: 'getLogFileContent/hasContent',
    }),
  },
  mounted() {
    if (!this.hasContent) {
      const args = {
        type: this.fileType,
        id:   this.reportId,
      };
      console.log(`fetching file contents: ${JSON.stringify(args)}`);
      this.getLogFileContentNow(args);
    }
  },
  methods: {
    ...mapActions({
      getLogFileContent: 'getLogFileContent/getLogFileContent',
    }),

    async getLogFileContentNow(args) {
      this.httpError = false;
      this.isLoading = true;
      try {
        await this.getLogFileContent(args);
      }
      catch (e) {
        this.httpError = true;
        console.log(`HTTP-Error: ${e}`);
      }
      logDebug(`getLogFileContentNow: ${this.file.content}`);

      this.isLoading = false;
    },
  },
}
</script>
